package org.homework.constants;

public interface Articles {
    String T_AND_C_ARTICLE_ENTERING_INTO_THE_PURCHASE_AND_SALE_AGREEMENT = "ENTERING INTO THE PURCHASE AND SALE AGREEMENT";
    String T_AND_C_ARTICLE_GENERAL_PROVISIONS = "GENERAL PROVISIONS";
    String T_AND_C_ARTICLE_DEFINITIONS = "DEFINITIONS";
    String T_AND_C_ARTICLE_RIGHTS_AND_OBLIGATIONS_OF_THE_SELLER = "RIGHTS AND OBLIGATIONS OF THE SELLER";
    String T_AND_C_ARTICLE_PROVISION_OF_INFORMATION = "PROVISION OF INFORMATION";
}
